CREATE TABLE /*_*/sgt_cities (
  id INT NOT NULL AUTO_INCREMENT,
  code VARCHAR(255) NOT NULL,
  code_geonames VARCHAR(255) NOT NULL,
  short_name VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  long_name VARCHAR(255) DEFAULT NULL,
  parent_id INT NOT NULL,
  population INT(11) DEFAULT 0,
  latitude VARCHAR(255) DEFAULT NULL,
  longtitude VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX code (code),
  UNIQUE INDEX code_geonames (code_geonames),
  UNIQUE INDEX parent_id (parent_id),
  UNIQUE INDEX code_parent_id (code, parent_id),
  UNIQUE INDEX code_geonames_parent_id (code_geonames, parent_id),
  UNIQUE INDEX name (name),
  UNIQUE INDEX short_name (short_name)
) /*$wgDbTableOptions*/;