CREATE TABLE /*_*/sgt_countries (
  id INT NOT NULL AUTO_INCREMENT,
  code VARCHAR(255) NOT NULL,
  code3 VARCHAR(10) NOT NULL,
  code_num SMALLINT DEFAULT NULL,
  code_geonames VARCHAR(255) DEFAULT NULL,
  area SMALLINT DEFAULT NULL,
  currency VARCHAR(255) DEFAULT NULL,
  phone_prefix INT(5) DEFAULT NULL,
  population INT(11) DEFAULT NULL,
  language VARCHAR(255) DEFAULT NULL,
  short_name VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  long_name VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX code (code),
  UNIQUE INDEX code3 (code3),
  UNIQUE INDEX code_geonames (code_geonames),
  UNIQUE INDEX code_num (code_num),
  UNIQUE INDEX name (name),
  UNIQUE INDEX short_name (short_name)
) /*$wgDbTableOptions*/;